server:
  servlet:
    context-path: /uol/api

spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

uol:
  codinome:
    url:
      json: https://raw.githubusercontent.com/uolhost/test-backEnd-Java/master/referencias/vingadores.json
      xml: https://raw.githubusercontent.com/uolhost/test-backEnd-Java/master/referencias/liga_da_justica.xml